# Generated by Django 4.2.2 on 2023-06-08 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('vcs_base_link', models.URLField(verbose_name='Базовая ссылка репозитория')),
                ('issue_tracker_link', models.URLField(verbose_name='Базовая ссылка на доску задач')),
            ],
            options={
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_token', models.TextField(verbose_name='Gitlab токен')),
                ('issue_tracker_token', models.TextField(verbose_name='Jira токен')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Доступы',
            },
        ),
    ]
