# Generated by Django 4.2.2 on 2023-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(default='https://t.me/vlelik', max_length=200, verbose_name='Проект менеджер'),
        ),
    ]
