# Generated by Django 4.2.2 on 2023-06-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='play_console_link',
            field=models.URLField(default='', verbose_name='Ссылка на Play Console'),
        ),
    ]
