# Generated by Django 4.2.2 on 2023-06-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
